# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path
from PyInstaller.building.build_main import Analysis, PYZ, EXE
import shutil

block_cipher = None

SPEC_DIR = Path(__file__).resolve().parent if '__file__' in globals() else Path.cwd()
LIB_DIR = SPEC_DIR / "Library"
DIST_DIR = SPEC_DIR / "dist"

# Bundle VERSION.txt (written by CI from the git tag, see build-executables.yml)
# next to the exe so RATS.py can read the real version at runtime. Falls back
# gracefully to the file's default version string if it isn't present, e.g.
# for local dev builds.
datas = []
version_txt = SPEC_DIR / "VERSION.txt"
if version_txt.exists():
    datas.append((str(version_txt), '.'))

# Windows file-properties version resource (Explorer -> Properties -> Details,
# and what the Inno Setup installer / Add-Remove Programs entry reflects too).
# Generated by CI on Windows only; ignored automatically on other platforms.
version_info_file = SPEC_DIR / "version_info.txt"
version_resource = str(version_info_file) if version_info_file.exists() else None

a = Analysis(
    ['RATS.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[
        'requests',
        'urllib3'
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)


exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    onefile=False,
    icon=str(SPEC_DIR / "Ratimg.ico"),
    version=version_resource
)
